version: '2.1'

services:
  web:
    image: notifier
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8000
    env_file:
      - .env
    volumes:
      - .:/app

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    volumes_from:
      - web

volumes:
  postgres_data: